name: CI

'on':
  pull_request:
  push:
    branches:
      - develop

jobs:
  build-praktiki-1-9:
    runs-on: ubuntu-latest
    env:
      working-directory: ./praktiki_1-9
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        working-directory: ${{env.working-directory}}
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./praktiki_1-9/gradlew
      - name: Build with Gradle
        run: ./praktiki_1-9/gradlew build
      - name: Run tests
        run: ./praktiki_1-9/gradlew test --warning-mode=all