name: CI

'on':
  pull_request:
  push:
    branches:
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew compileJava compileTestJava
  
  tests:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test --warning-mode=all
      - name: upload html test report
        uses: actions/upload-artifact@v4.3.1
        with: 
            name: test
            path: app/build/reports/tests/testDebugUnitTest/
